name: xLaunchPads
main: dev.drygo.XLaunchPads.XLaunchPads
version: 1.0.1
api-version: 1.20
authors: [Drygo]
commands:
  xlaunchpads:
    description: "xLaunchPads main command"
permissions:
  xlaunchpads.admin:
    description: "xLaunchPads admin permission"
    default: false
    children:
      xlaunchpads.command.help:
       default: false
      xlaunchpads.command.reload:
        default: false
      xlaunchpads.command.set:
        default: false
      xlaunchpads.command.info:
        default: false