name: xLaunchPads
main: org.eldrygo.XLaunchPads.XLaunchPads
version: 0.0.02
api-version: 1.21
authors: [Drygo]
commands:
  xlaunchpads:
    description: "xLaunchPads main command"
    permission: xlaunchpads.admin
permissions:
  xlaunchpads.admin:
    description: "xLaunchPads admin permission"
    default: false